from pathlib import Path

from typer.main import get_command

import cli.main as cli_main
from app.main import app
from app.services.project_status_service import build_api_inventory
from scripts import smoke_test_api as smoke


SUMMARY = Path("docs/PUBLIC_RELEASE_SUMMARY.md")


def test_public_release_summary_declares_public_boundaries() -> None:
    text = SUMMARY.read_text(encoding="utf-8")

    required_phrases = [
        "Ollama local API only",
        "외부 LLM API: 사용하지 않음",
        "운영 배포: 하지 않음",
        "클라우드/Oracle 리소스: 연결 또는 생성하지 않음",
        "## 기능 경계 요약",
        "Agent read-only execution v1",
        "조건부 기능",
        "허용 root 폴더 목록 조회",
        "텍스트 파일 preview",
        "명시 URL 단건 read-only fetch",
        "dry-run only",
        "폴더 UI 열기",
        "브라우저 클릭/입력/전송 자동화",
        "실제 shell 실행",
        "파일 생성/수정/삭제 자동화",
        "repair-preview",
        "다중 사용자 auth/RBAC",
        "HTTPS termination",
    ]

    assert SUMMARY.exists()
    for phrase in required_phrases:
        assert phrase in text

    assert "배포 완료" not in text
    assert "LOCAL_API_KEY=" not in text


def test_public_release_summary_separates_done_preview_and_out_of_scope() -> None:
    text = SUMMARY.read_text(encoding="utf-8")
    snapshot = text.split("## 공개용 상태 스냅샷", 1)[1].split("## 기능 경계 요약", 1)[0]

    for phrase in [
        "로컬 API 서버",
        "구현됨",
        "문서 기반 RAG",
        "PDF OCR fallback",
        "PyPDF image XObject",
        "CLI 로컬 비서",
        "Agent 실행 엔진",
        "preview-only",
        "배포/외부 자동화",
        "하지 않음",
        "실제 shell/file/browser 실행은 하지 않는다",
        "운영 배포",
        "외부 LLM API",
    ]:
        assert phrase in snapshot


def test_public_release_summary_keeps_private_data_and_verification_visible() -> None:
    text = SUMMARY.read_text(encoding="utf-8")

    private_paths = [
        ".env",
        "data/local_ai.sqlite3",
        "data/chroma/",
        "data/uploads/",
        "data/logs/",
        "data/*.jsonl",
        ".sentryclirc",
        ".config/containers/auth.json",
        ".config/helm/registry/config.json",
        ".config/helm/repositories.yaml",
        ".config/hub",
    ]
    verification_commands = [
        ".venv/bin/pytest",
        ".venv/bin/python -m compileall app cli scripts",
        ".venv/bin/python scripts/public_release_check.py --root . --json",
        ".venv/bin/python scripts/local_ci_check.py --root .",
        "git diff --check",
    ]

    for item in private_paths + verification_commands:
        assert item in text

    assert "815 passed, 1 warning" in text
    assert "814 passed, 1 warning" not in text
    assert "813 passed, 1 warning" not in text
    assert "812 passed, 1 warning" not in text
    assert "811 passed, 1 warning" not in text
    assert "810 passed, 1 warning" not in text
    assert "809 passed, 1 warning" not in text
    assert "808 passed, 1 warning" not in text
    assert "807 passed, 1 warning" not in text
    assert "806 passed, 1 warning" not in text
    assert "805 passed, 1 warning" not in text
    assert "804 passed, 1 warning" not in text
    assert "803 passed, 1 warning" not in text
    assert "802 passed, 1 warning" not in text
    assert "801 passed, 1 warning" not in text
    assert "800 passed, 1 warning" not in text
    assert "780 passed, 1 warning" not in text
    assert "778 passed, 1 warning" not in text
    assert "776 passed, 1 warning" not in text
    assert "774 passed, 1 warning" not in text
    assert "772 passed, 1 warning" not in text
    assert "770 passed, 1 warning" not in text
    assert "768 passed, 1 warning" not in text
    assert "767 passed, 1 warning" not in text
    assert "766 passed, 1 warning" not in text
    assert "765 passed, 1 warning" not in text
    assert "623 passed, 1 warning" not in text
    for phrase in [
        "91차 Commit / Stage Decision Required",
        "Commit / Stage Decision Required packet",
        "stage/commit/push decision boundary",
        "commit scope",
        "commit message",
        "push/PR 여부",
        "사용자 최종 승인 필요",
        "modified tracked files 40개",
        "untracked docs 11개",
        "stage/commit/push 미수행",
        "92차 Commit Approval or Jarvis v1 Safe Planning",
        "멈추지 말고 해줘",
        "git 작업 명시 승인으로 해석하지 않고",
        "commit approval flow는 사용자 명시 승인 전 blocked",
        "Jarvis v1 Safe Planning은 safe planning only",
        "docs/test/review-required 중심",
        "120차 Jarvis v1 실사용형 목표까지 28차 남음",
        "150차 Jarvis v2 완성권까지 58차 남음",
        "actual action 없이 stage/commit/push 미수행",
        "93차 Jarvis v1 Safe Roadmap Drift Guard",
        "93~120차 Jarvis v1 실사용형 구간은 safe-next/review-required/blocked 경계",
        "roadmap drift guard",
        "actual action으로 새지 않게 막는 문서/테스트 guard",
        "120차 Jarvis v1 실사용형 목표까지 27차 남음",
        "150차 Jarvis v2 완성권까지 57차 남음",
        "94차 Jarvis v1 Capability Honesty Guard",
        "실제 열린 기능, env opt-in 기능, blocked 기능",
        "Jarvis v1은 실행형 완성 제품이 아니라 safe-local assistant boundary",
        "이미 열린 기능처럼 과장하지 않게",
        "120차 Jarvis v1 실사용형 목표까지 26차 남음",
        "150차 Jarvis v2 완성권까지 56차 남음",
        "95차 Jarvis v1 Manual UX Contract Guard",
        "수동 UX",
        "approval wording",
        "blocked state",
        "approval 상태 변경은 실행 승인으로 오해되면 안 되고",
        "manual UX는 operator review surface",
        "connector dispatch, approval consume, browser actual interaction, app-os actual action으로 승격하지 않는다",
        "120차 Jarvis v1 실사용형 목표까지 25차 남음",
        "150차 Jarvis v2 완성권까지 55차 남음",
        "96차 Jarvis v1 Evidence Packet Guard",
        "증거 패킷",
        "actual verification results",
        "disabled boundary",
        "remaining Decision Required",
        "실행하지 않은 검증/빌드/배포/실제 action",
        "완료처럼 표현하지 않는다",
        "120차 Jarvis v1 실사용형 목표까지 24차 남음",
        "150차 Jarvis v2 완성권까지 54차 남음",
        "97차 Jarvis v1 Decision Required Packet Guard",
        "commit/browser/app-os/action-loop/durable activation Decision Required",
        "증거 패킷과 handoff",
        "사용자 최종 승인이나 Opus review가 필요한 항목",
        "safe-next 작업으로 오분류하지 않는다",
        "120차 Jarvis v1 실사용형 목표까지 23차 남음",
        "150차 Jarvis v2 완성권까지 53차 남음",
        "98차 Jarvis v1 Approval Wording Drift Guard",
        "approval wording이 실행 승인, 상태 변경, 검증 완료, Decision Required를 혼동하지 않",
        "approval 상태 변경, approved console state, confirmation state",
        "execution approval로 승격되지 않는다",
        "approval-wording-is-not-execution-approval",
        "state-change-is-not-execution-approval",
        "verification-pass-is-not-activation-approval",
        "120차 Jarvis v1 실사용형 목표까지 22차 남음",
        "150차 Jarvis v2 완성권까지 52차 남음",
        "99차 Jarvis v1 Release-lock Drift Guard",
        "92~98차 Jarvis v1 safe guard 누적 경계",
        "stage/commit/push 미수행 상태",
        "durable execution이 다시 열리지 않았는지 guard",
        "modified tracked files 40개",
        "untracked docs 11개",
        "staged diff 없음",
        "120차 Jarvis v1 실사용형 목표까지 21차 남음",
        "150차 Jarvis v2 완성권까지 51차 남음",
        "100차 Jarvis v1 Final Verification Sweep",
        "92~99차 Jarvis v1 safe guard 구간",
        "full pytest",
        "compileall",
        "public release check",
        "git diff check",
        "local CI",
        "git status",
        "finding 없음",
        "120차 Jarvis v1 실사용형 목표까지 20차 남음",
        "150차 Jarvis v2 완성권까지 50차 남음",
        "101차 Jarvis v1 Commit Readiness Packet",
        "92~100차 Jarvis v1 safe guard 구간",
        "commit scope",
        "commit message",
        "push/PR 여부",
        "사용자 최종 승인 필요 상태",
        "120차 Jarvis v1 실사용형 목표까지 19차 남음",
        "150차 Jarvis v2 완성권까지 49차 남음",
        "102차 Jarvis v1 Handoff Freeze",
        "92~101차 Jarvis v1 safe guard 구간",
        "다음 handoff와 검증 프롬프트",
        "Ready-to-send prompt",
        "1~101차 완료 상태",
        "stage101/stage102 docs contract",
        "120차 Jarvis v1 실사용형 목표까지 18차 남음",
        "150차 Jarvis v2 완성권까지 48차 남음",
        "103차 Jarvis v1 Release Candidate Prep",
        "92~102차 Jarvis v1 safe guard 구간",
        "release candidate readiness",
        "남은 Decision Required",
        "stage/commit/push 사용자 최종 승인 필요 상태",
        "120차 Jarvis v1 실사용형 목표까지 17차 남음",
        "150차 Jarvis v2 완성권까지 47차 남음",
        "104차 Jarvis v1 Final RC Verification",
        "92~103차 Jarvis v1 safe guard 구간",
        "full verification",
        "RC boundary",
        "`815 passed, 1 warning`",
        "public release check `ok=true`",
        "`scanned_files=134`",
        "120차 Jarvis v1 실사용형 목표까지 16차 남음",
        "150차 Jarvis v2 완성권까지 46차 남음",
        "105차 Jarvis v1 Final Stage Decision Packet",
        "Jarvis v1 RC 구간",
        "stage/commit/push 최종 Decision Required",
        "commit scope, commit message, push/PR 여부",
        "사용자 최종 승인 필요 상태",
        "stage/commit/push는 수행하지 않았다",
        "120차 Jarvis v1 실사용형 목표까지 15차 남음",
        "150차 Jarvis v2 완성권까지 45차 남음",
        "106차 Jarvis v1 Public Release Guard",
        "public release scanner",
        "공개 문서의 Jarvis v1 안전 경계",
        "public release check `ok=true`",
        "`scanned_files=134`",
        "finding 없음",
        "120차 Jarvis v1 실사용형 목표까지 14차 남음",
        "150차 Jarvis v2 완성권까지 44차 남음",
        "107차 Jarvis v1 Evidence Freeze",
        "Jarvis v1 RC 증거 패킷",
        "검증 수치",
        "815 passed, 1 warning",
        "public release check `ok=true`",
        "`scanned_files=134`",
        "finding 없음",
        "120차 Jarvis v1 실사용형 목표까지 13차 남음",
        "150차 Jarvis v2 완성권까지 43차 남음",
        "108차 Jarvis v1 Release Lock Refresh",
        "92~107차 Jarvis v1 RC 구간",
        "release lock",
        "남은 Decision Required",
        "commit scope",
        "commit message",
        "push/PR 여부",
        "120차 Jarvis v1 실사용형 목표까지 12차 남음",
        "150차 Jarvis v2 완성권까지 42차 남음",
        "109차 Jarvis v1 Final Handoff Refresh",
        "108차 release lock 결과",
        "110차 다음 작업 프롬프트",
        "handoff refresh",
        "120차 Jarvis v1 실사용형 목표까지 11차 남음",
        "150차 Jarvis v2 완성권까지 41차 남음",
        "110차 Jarvis v1 Verification Refresh",
        "Jarvis v1 RC 구간의 최신 검증 수치",
        "public release scanner 기준",
        "public release check `ok=true`",
        "`scanned_files=134`",
        "finding 없음",
        "120차 Jarvis v1 실사용형 목표까지 10차 남음",
        "150차 Jarvis v2 완성권까지 40차 남음",
        "111차 Jarvis v1 Commit Boundary Refresh",
        "commit scope/message/push/PR 사용자 최종 승인 경계",
        "commit scope",
        "commit message",
        "push/PR 여부",
        "사용자 최종 승인 필요 상태",
        "stage/commit/push는 수행하지 않았다",
        "120차 Jarvis v1 실사용형 목표까지 9차 남음",
        "150차 Jarvis v2 완성권까지 39차 남음",
        "112차 Jarvis v1 Final Verification Packet",
        "Jarvis v1 RC 구간의 최종 검증 packet",
        "남은 Decision Required",
        "actual verification results",
        "disabled boundary",
        "remaining Decision Required",
        "stage/commit/push approval boundary",
        "modified tracked files 40개",
        "untracked docs 11개",
        "staged diff 없음",
        "stage/commit/push는 수행하지 않았다",
        "commit scope",
        "commit message",
        "push/PR 여부",
        "사용자 최종 승인 필요 상태",
        "120차 Jarvis v1 실사용형 목표까지 8차 남음",
        "150차 Jarvis v2 완성권까지 38차 남음",
        "113차 Jarvis v1 Release Readiness Closure",
        "release readiness",
        "commit 전 닫힘 상태",
        "public release check clean",
        "full pytest green",
        "compileall green",
        "git diff check green",
        "local CI green",
        "staged diff 없음",
        "commit scope, commit message, push/PR 여부",
        "사용자 최종 승인 필요 상태",
        "stage/commit/push가 미수행",
        "modified tracked files 40개",
        "untracked docs 11개",
        "120차 Jarvis v1 실사용형 목표까지 7차 남음",
        "150차 Jarvis v2 완성권까지 37차 남음",
        "114차 Jarvis v1 Commit Approval Decision Packet",
        "commit approval 전 사용자 최종 승인 필요 항목",
        "commit scope, commit message, push/PR 여부는 Decision Required",
        "사용자 최종 승인 필요 상태",
        "stage/commit/push는 수행하지 않았고 사용자 명시 승인 전 수행하지 않는다",
        "`git diff --cached --quiet` 기준 staged diff 없음",
        "modified tracked files 40개",
        "untracked docs 11개",
        "815 passed, 1 warning",
        "public release check `ok=true`",
        "`scanned_files=134`",
        "finding 없음",
        "120차 Jarvis v1 실사용형 목표까지 6차 남음",
        "150차 Jarvis v2 완성권까지 36차 남음",
        "115차 Jarvis v1 Pre-120 Remaining Scope Plan",
        "120차 Jarvis v1 실사용형 목표까지 남은 safe-next 범위",
        "115~120차 남은 작업",
        "docs/test/review-required 중심",
        "116차 Pre-120 Verification Matrix",
        "117차 Pre-120 Handoff Sync",
        "118차 Pre-120 Final Evidence Refresh",
        "119차 Jarvis v1 Readiness Freeze",
        "120차 Jarvis v1 실사용형 목표 Decision Packet",
        "docs contract",
        "public release summary count guard",
        "local CI 유지",
        "stage/commit/push 미수행 guard",
        "disabled boundary guard",
        "review-required 범위",
        "durable execution activation",
        "120차 Jarvis v1 실사용형 목표까지 5차 남음",
        "150차 Jarvis v2 완성권까지 35차 남음",
        "116차 Jarvis v1 Pre-120 Verification Matrix",
        "116~120차 남은 safe-next 검증 matrix",
        "stage contract",
        "docs bundle",
        "full pytest",
        "compileall",
        "public release check",
        "git diff --check",
        "local CI",
        "git status",
        "staged diff 없음 guard",
        "117~120차는 매 차수",
        "modified tracked files 40개",
        "untracked docs 11개",
        "stage/commit/push 사용자 최종 승인 필요 상태",
        "commit scope/message/push/PR Decision Required",
        "actual action 활성화 승인으로 해석하지 않는다",
        "120차 Jarvis v1 실사용형 목표까지 4차 남음",
        "150차 Jarvis v2 완성권까지 34차 남음",
        "117차 Jarvis v1 Pre-120 Handoff Sync",
        "118차 다음 handoff와 검증 프롬프트",
        "116차 검증 matrix가 NEXT_CHAT_HANDOFF, TASKS, WORKLOG, PUBLIC_RELEASE_SUMMARY에 남아",
        "118차 다음 작업은 Jarvis v1 Pre-120 Final Evidence Refresh",
        "stage117 contract",
        "docs bundle",
        "full pytest",
        "compileall",
        "public release check",
        "git diff --check",
        "local CI",
        "git status",
        "staged diff 없음 guard",
        "120차 Jarvis v1 실사용형 목표까지 3차 남음",
        "150차 Jarvis v2 완성권까지 33차 남음",
        "118차 Jarvis v1 Pre-120 Final Evidence Refresh",
        "120차 직전 evidence 기준",
        "evidence 기준은 full pytest, public release check, local CI, staged diff 없음, modified tracked files 40개, untracked docs 11개",
        "compileall 성공",
        "git diff --check 성공",
        "local CI 성공",
        "stage/commit/push는 수행하지 않았고 사용자 명시 승인 전 수행하지 않는다",
        "commit scope, commit message, push/PR 여부는 사용자 최종 승인 필요 상태",
        "120차 Jarvis v1 실사용형 목표까지 2차 남음",
        "150차 Jarvis v2 완성권까지 32차 남음",
        "119차 Jarvis v1 Readiness Freeze",
        "120차 Jarvis v1 실사용형 목표 진입 직전 readiness 상태",
        "readiness freeze 기준은 evidence 기준, disabled boundary, remaining Decision Required, stage/commit/push 미수행",
        "readiness freeze는 activation approval이 아니며",
        "durable storage migration/table/worker/replay/recovery도 열지 않는다",
        "compileall 성공",
        "git diff --check 성공",
        "local CI 성공",
        "120차 Jarvis v1 실사용형 목표까지 1차 남음",
        "150차 Jarvis v2 완성권까지 31차 남음",
        "120차 Jarvis v1 실사용형 목표 Decision Packet",
        "Jarvis v1 safe-local assistant boundary 완성권",
        "Jarvis v1 실사용형 목표는 실행형 완성 제품이 아니며",
        "실제 열린 기능, env opt-in 기능, blocked 기능, remaining Decision Required",
        "실제 열린 기능은 로컬 RAG/assistant bridge",
        "protected approval-console read-only API",
        "durable-state-preview read-only API 하나",
        "env opt-in 기능은 read-only adapter, read-only action-loop dispatch, allowlist shell",
        "browser observe metadata",
        "browser limited candidate validation",
        "external web search provider 단건 search",
        "blocked 기능은 browser actual interaction, app-os actual action, action-loop full dispatch",
        "durable execution, durable storage migration/table/worker/replay/recovery",
        "Jarvis v1 Decision Packet은 activation approval이 아니며",
        "stage/commit/push는 수행하지 않았다",
        "modified tracked files 40개",
        "untracked docs 11개",
        "staged diff 없음",
        "150차 Jarvis v2 완성권까지 30차 남음",
        "121차 Jarvis v2 Entry Scope Plan",
        "121~150차 v2 완성권 범위를 safe-next/review-required/blocked 경계로 분류",
        "safe-next 범위는 docs contract, public release summary guard, local CI 유지",
        "runtime/docs drift guard",
        "capability honesty guard",
        "approval wording guard",
        "evidence packet refresh",
        "handoff sync",
        "review-required 범위는 commit approval, browser actual interaction candidate",
        "app-os actual action candidate",
        "action-loop full dispatch candidate",
        "durable execution candidate",
        "외부 provider 확장",
        "Oracle/cloud/cost 영향 작업",
        "blocked 범위는 사용자 최종 승인과 Opus review 전 browser actual interaction",
        "durable storage migration/table/worker/replay/recovery, autonomous replay/recovery",
        "actual action activation roadmap이 아니라 safe-local hardening roadmap",
        "122~130차는 v2 safety/contract hardening",
        "131~140차는 v2 evidence/release-lock hardening",
        "141~150차는 v2 final decision/release-lock packet",
        "150차 Jarvis v2 완성권까지 29차 남음",
        "122차 Jarvis v2 Safety Contract Matrix",
        "v2 안전 계약과 disabled boundary matrix",
        "safe-next matrix 항목은 docs contract, public release summary guard, local CI 유지",
        "runtime/docs drift guard, capability honesty guard, approval wording guard",
        "evidence packet refresh, handoff sync",
        "review-required matrix 항목은 commit approval, browser actual interaction candidate",
        "app-os actual action candidate, action-loop full dispatch candidate, durable execution candidate",
        "external provider expansion, production deployment, Oracle/cloud/cost impact work",
        "blocked matrix 항목은 사용자 최종 승인과 Opus review 전 browser actual interaction",
        "daemon/service/background loop, durable storage migration/table/worker/replay/recovery",
        "autonomous replay/recovery",
        "disabled boundary matrix는 `FULL_AUTOMATION_DISPATCH_ENABLED=false`",
        "`action_loop_full_dispatch_connected=false`",
        "`browser_actual_interaction_connected=false`",
        "`app_os_actual_action_connected=false`",
        "`durable_execution_connected=false`",
        "v2 safety matrix는 activation approval이 아니며",
        "approval 상태 변경, manual review packet, confirmation wording, passing verification",
        "execution approval로 승격하지 않는다",
        "150차 Jarvis v2 완성권까지 28차 남음",
        "123차 Jarvis v2 Runtime Docs Drift Guard",
        "`/assistant/capabilities`, README, SECURITY, PUBLIC_RELEASE_SUMMARY, NEXT_CHAT_HANDOFF",
        "disabled boundary wording이 서로 어긋나지 않게 유지",
        "capability honesty 기준은 실제 열린 기능, env opt-in 기능, blocked 기능, remaining Decision Required를 구분",
        "`/assistant/capabilities`와 문서는 browser actual interaction, app-os actual action, action-loop full dispatch",
        "daemon/service/background loop, durable execution을 enabled로 광고하지 않는다",
        "v2 drift guard는 `FULL_AUTOMATION_DISPATCH_ENABLED=false`",
        "`action_loop_full_dispatch_connected=false`",
        "`browser_actual_interaction_connected=false`",
        "`app_os_actual_action_connected=false`",
        "`durable_execution_connected=false`를 유지한다",
        "passing verification이 activation approval이 아니며 stage/commit/push approval도 아님",
        "route/API/schema/service 변경 없이 docs/test/review-required 중심",
        "150차 Jarvis v2 완성권까지 27차 남음",
        "124차 Jarvis v2 Capability Honesty Refresh",
        "실제 열린 기능, env opt-in 기능, blocked 기능, remaining Decision Required 문구를 재동기화",
        "실제 열린 기능은 로컬 RAG/assistant bridge",
        "preview/dry-run/read-only/state-only endpoint",
        "protected approval-console read-only API",
        "durable-state-preview read-only API 하나",
        "env opt-in 기능은 read-only adapter, read-only action-loop dispatch, allowlist shell",
        "single-file patch",
        "single-file rollback",
        "one-shot task queue",
        "browser observe metadata",
        "browser limited candidate validation",
        "external web search provider 단건 search",
        "blocked 기능은 browser actual interaction, app-os actual action, action-loop full dispatch",
        "durable execution, durable storage migration/table/worker/replay/recovery, autonomous replay/recovery",
        "remaining Decision Required는 commit approval, browser actual/app-os actual/action-loop full dispatch/durable execution activation",
        "external provider expansion, production deployment, Oracle/cloud/cost impact work",
        "Jarvis v2 wording은 actual action 제품으로 과장하지 않고 safe-local hardening roadmap",
        "150차 Jarvis v2 완성권까지 26차 남음",
        "125차 Jarvis v2 Approval Wording Guard",
        "approval/confirmation/verification wording이 execution approval로 승격되지 않게",
        "approval state, approved console state, operator confirmation, passing verification, manual review packet은 actual connector dispatch approval이 아니다",
        "approval 상태 변경은 execution approval이 아니며 approval 상태만으로 connector execution",
        "approval consume, browser actual interaction, app-os actual action, action-loop full dispatch, durable execution을 시작할 수 없다",
        "operator confirmation wording은 final human action boundary를 설명할 수 있지만 local server actual action authorization으로 해석하지 않는다",
        "passing verification은 activation approval이 아니며 public release check green",
        "full pytest green, compileall green, local CI green은 stage/commit/push approval도 아니다",
        "manual review packet과 evidence packet은 remaining Decision Required를 보여 주는 review artifact",
        "execution approval이나 production readiness approval이 아니다",
        "approval-wording-is-not-execution-approval",
        "confirmation-is-not-execution-approval",
        "verification-pass-is-not-activation-approval",
        "150차 Jarvis v2 완성권까지 25차 남음",
        "126차 Jarvis v2 Evidence Packet Refresh",
        "actual verification results, disabled boundary, remaining Decision Required 증거 패킷을 함께 갱신",
        "actual verification results는 `815 passed, 1 warning`, public release check `ok=true`, `scanned_files=134`",
        "finding 없음, compileall 성공, git diff check 성공, local CI 성공",
        "evidence packet은 실행하지 않은 검증/빌드/배포/실제 action을 완료처럼 표현하지 않는다",
        "disabled boundary는 browser actual interaction, app-os actual action, action-loop full dispatch",
        "durable execution, durable storage migration/table/worker/replay/recovery, autonomous replay/recovery가 열리지 않았음을 포함",
        "remaining Decision Required는 commit approval, browser actual/app-os actual/action-loop full dispatch/durable execution activation",
        "external provider expansion, production deployment, Oracle/cloud/cost impact work",
        "evidence packet은 activation approval, production readiness approval, stage/commit/push approval이 아니다",
        "public release check clean, full pytest green, compileall green, git diff check green, local CI green, staged diff 없음",
        "150차 Jarvis v2 완성권까지 24차 남음",
        "127차 Jarvis v2 Handoff Sync",
        "126차 evidence packet과 다음 검증 프롬프트를 `docs/NEXT_CHAT_HANDOFF.md`에 동기화",
        "Ready-to-send prompt는 1~126차 완료 상태, actual verification results, disabled boundary, remaining Decision Required, stage/commit/push 미수행을 포함",
        "Ready-to-send prompt는 `815 passed, 1 warning`, public release check `ok=true`, `scanned_files=134`",
        "modified tracked files 40개, untracked docs 11개, staged diff 없음 기준을 포함",
        "다음 검증 프롬프트는 stage126/stage127 docs contract, docs bundle, full pytest",
        "compileall, public release check, git diff --check, local CI, git status, staged diff 없음 guard를 포함",
        "handoff sync는 activation approval, production readiness approval, stage/commit/push approval이 아니다",
        "browser actual interaction, app-os actual action, action-loop full dispatch, daemon/service/background loop, durable execution",
        "durable storage migration/table/worker/replay/recovery는 계속 disabled boundary에 남긴다",
        "150차 Jarvis v2 완성권까지 23차 남음",
        "128차 Jarvis v2 Release-lock Drift Guard",
        "121~127차 v2 safe guard 누적 경계와 stage/commit/push 미수행 상태를 재확인",
        "121~127차 v2 safe guard는 entry scope plan, safety contract matrix, runtime/docs drift guard",
        "capability honesty refresh, approval wording guard, evidence packet refresh, handoff sync",
        "v2 safe guard 누적 경계는 actual action activation roadmap이 아니라 safe-local hardening roadmap",
        "browser actual interaction, app-os actual action, action-loop full dispatch, daemon/service/background loop, durable execution은 다시 열리지 않았다",
        "durable storage migration/table/worker/replay/recovery, autonomous replay/recovery, external provider expansion",
        "production deployment, Oracle/cloud/cost impact work는 remaining Decision Required",
        "`FULL_AUTOMATION_DISPATCH_ENABLED=false`",
        "`action_loop_full_dispatch_connected=false`",
        "`browser_actual_interaction_connected=false`",
        "`app_os_actual_action_connected=false`",
        "`durable_execution_connected=false`",
        "150차 Jarvis v2 완성권까지 22차 남음",
        "129차 Jarvis v2 Final Verification Sweep",
        "121~128차 v2 safe guard 구간의 full verification과 release-lock boundary를 재확인",
        "full verification은 stage129 docs contract, docs bundle, full pytest, compileall",
        "public release check, git diff --check, local CI, git status, staged diff 없음 guard를 포함",
        "최신 검증 기준은 `815 passed, 1 warning`, public release check `ok=true`, `scanned_files=134`, finding 없음",
        "compileall 성공, git diff --check 성공, local CI 성공, staged diff 없음 기준을 유지",
        "release-lock boundary는 121~128차 v2 safe guard가 actual action activation roadmap이 아니라 safe-local hardening roadmap",
        "browser actual interaction, app-os actual action, action-loop full dispatch, daemon/service/background loop, durable execution",
        "durable storage migration/table/worker/replay/recovery는 열리지 않았다",
        "150차 Jarvis v2 완성권까지 21차 남음",
        "130차 Jarvis v2 Commit Readiness Packet",
        "121~129차 v2 safe guard 구간의 commit scope/message/push/PR Decision Required를 정리",
        "commit scope 후보는 121~129차 v2 safe guard 문서/테스트 갱신",
        "runtime route/API/schema/service 변경을 새로 열지 않는다",
        "commit message 후보는 `Document Jarvis v2 safe guard readiness packet`",
        "최종 commit message는 사용자 승인 필요 상태",
        "push/PR 여부는 사용자 최종 승인 필요 상태",
        "Codex가 임의로 push/PR을 만들지 않는다",
        "stage/commit/push는 수행하지 않았고 staged diff 없음 기준을 유지",
        "release readiness는 activation approval, production readiness approval, stage/commit/push approval이 아니다",
        "150차 Jarvis v2 완성권까지 20차 남음",
        "131차 Jarvis v2 Evidence Lock Refresh",
        "121~130차 v2 safe guard 구간의 evidence/release readiness 기준을 재확인",
        "evidence lock은 actual verification results, disabled boundary, remaining Decision Required, commit readiness boundary를 함께 포함",
        "actual verification results는 `815 passed, 1 warning`, public release check `ok=true`, `scanned_files=134`",
        "finding 없음, compileall 성공, git diff --check 성공, local CI 성공",
        "disabled boundary는 browser actual interaction, app-os actual action, action-loop full dispatch",
        "durable execution, durable storage migration/table/worker/replay/recovery가 열리지 않았음을 포함",
        "remaining Decision Required는 commit approval, browser actual/app-os actual/action-loop full dispatch/durable execution activation",
        "commit readiness boundary는 commit scope 후보, commit message 후보, push/PR 여부가 사용자 최종 승인 필요 상태",
        "150차 Jarvis v2 완성권까지 19차 남음",
        "132차 Jarvis v2 Release Readiness Drift Guard",
        "121~131차 v2 safe guard 구간의 release readiness 문구가 activation approval로 새지 않게 재확인",
        "release readiness는 public release check clean, full pytest green, compileall green",
        "git diff check green, local CI green, staged diff 없음 기준을 의미",
        "release readiness는 activation approval, production readiness approval, stage/commit/push approval이 아니다",
        "release readiness는 browser actual interaction, app-os actual action, action-loop full dispatch, durable execution activation approval로 해석하지 않는다",
        "`815 passed, 1 warning`, public release check `ok=true`, `scanned_files=134`, finding 없음 기준을 유지",
        "150차 Jarvis v2 완성권까지 18차 남음",
        "133차 Jarvis v2 Public Release Evidence Refresh",
        "public release evidence는 public release check clean, `scanned_files=134`, finding 없음",
        "private data exclusion, disabled actual action boundary를 함께 포함",
        "public release evidence는 production deployment approval, external provider expansion approval, stage/commit/push approval이 아니다",
        "private data exclusion은 `.env`, credential, local DB, Chroma data, uploads/logs",
        "raw private documents, API key/token/password/private key를 공개하지 않는 기준",
        "disabled actual action boundary는 browser actual interaction, app-os actual action, action-loop full dispatch",
        "daemon/service/background loop, durable execution, durable storage migration/table/worker/replay/recovery를 계속 열지 않는 기준",
        "150차 Jarvis v2 완성권까지 17차 남음",
        "134차 Jarvis v2 Disabled Boundary Evidence Guard",
        "disabled actual action boundary와 remaining Decision Required를 재확인",
        "Disabled Boundary Evidence Guard",
        "remaining Decision Required는 commit approval, browser actual/app-os actual/action-loop full dispatch/durable execution activation",
        "external provider expansion, production deployment, Oracle/cloud/cost impact work",
        "disabled boundary evidence는 activation approval, production readiness approval, stage/commit/push approval이 아니다",
        "`FULL_AUTOMATION_DISPATCH_ENABLED=false`",
        "`action_loop_full_dispatch_connected=false`",
        "`browser_actual_interaction_connected=false`",
        "`app_os_actual_action_connected=false`",
        "`durable_execution_connected=false`",
        "150차 Jarvis v2 완성권까지 16차 남음",
        "135차 Jarvis v2 Remaining Decision Required Sync",
        "remaining Decision Required 항목과 handoff/public release evidence를 재동기화",
        "Remaining Decision Required Sync",
        "handoff/public release evidence는 actual verification results, disabled boundary, remaining Decision Required, stage/commit/push 미수행을 함께 포함",
        "commit approval remains Decision Required",
        "browser actual/app-os actual/action-loop full dispatch/durable execution activation remains Decision Required",
        "external provider expansion, production deployment, Oracle/cloud/cost impact work remains Decision Required",
        "remaining Decision Required sync는 activation approval, production readiness approval, stage/commit/push approval이 아니다",
        "150차 Jarvis v2 완성권까지 15차 남음",
        "136차 Jarvis v2 Release Evidence Consistency Guard",
        "release evidence와 remaining Decision Required 문구의 정합성을 재확인",
        "Release Evidence Consistency Guard",
        "release evidence는 actual verification results, disabled boundary, remaining Decision Required, public release check clean, staged diff 없음, stage/commit/push 미수행을 함께 포함",
        "release evidence consistency는 activation approval, production readiness approval, stage/commit/push approval이 아니다",
        "release evidence wording must not imply activation approval, production readiness approval, external provider approval, or git approval",
        "150차 Jarvis v2 완성권까지 14차 남음",
        "137차 Jarvis v2 Pre-final Evidence Freeze",
        "141~150차 final decision 구간 전 evidence 기준을 동결",
        "Pre-final Evidence Freeze",
        "frozen evidence 기준은 `815 passed, 1 warning`, public release check `ok=true`, `scanned_files=134`",
        "finding 없음, modified tracked files 40개, untracked docs 11개, staged diff 없음",
        "frozen evidence는 activation approval, production readiness approval, stage/commit/push approval, external provider approval이 아니다",
        "pre-final evidence freeze는 final decision approval이 아니라 141~150차 final decision 구간 전 evidence baseline",
        "150차 Jarvis v2 완성권까지 13차 남음",
        "138차 Jarvis v2 Final Decision Prep Boundary Guard",
        "final decision 준비 문구가 activation approval, production readiness approval, stage/commit/push approval로 새지 않게",
        "Final Decision Prep Boundary Guard",
        "final decision prep은 141~150차 final decision 구간을 준비하는 문서/테스트 guard이며 actual activation이 아니다",
        "final decision prep is not approval, final decision prep is not production readiness, final decision prep is not git approval",
        "150차 Jarvis v2 완성권까지 12차 남음",
        "139차 Jarvis v2 Final Decision Readiness Matrix",
        "141~150차 final decision 구간 진입 전 readiness matrix를 고정",
        "Final Decision Readiness Matrix",
        "readiness matrix는 evidence ready, disabled boundary ready, remaining Decision Required ready, git approval blocked, activation approval blocked를 구분",
        "readiness matrix는 activation approval, production readiness approval, stage/commit/push approval이 아니다",
        "readiness matrix ready 상태는 실제 activation, production deployment, external provider expansion, stage/commit/push 승인으로 해석하지 않는다",
        "150차 Jarvis v2 완성권까지 11차 남음",
        "140차 Jarvis v2 Pre-final Verification Refresh",
        "141~150차 final decision 구간 전 검증 기준을 재확인",
        "Pre-final Verification Refresh",
        "검증 기준은 `815 passed, 1 warning`, public release check `ok=true`, `scanned_files=134`, finding 없음, compileall 성공, git diff --check 성공, local CI 성공, staged diff 없음",
        "pre-final verification refresh는 activation approval, production readiness approval, stage/commit/push approval이 아니다",
        "pre-final verification refresh는 141~150차 final decision 구간 전 검증 기준 재확인이며 actual activation이 아니다",
        "browser actual/app-os actual/action-loop full dispatch/durable execution activation remains Decision Required",
        "external provider expansion, production deployment, Oracle/cloud/cost impact work remains Decision Required",
        "browser actual interaction/app-os actual action/git reset/bulk restore/daemon/service/운영 배포 blocked",
        "150차 Jarvis v2 완성권까지 10차 남음",
        "141차 Jarvis v2 Final Decision Entry Packet",
        "141~150차 final decision 구간 진입 packet을 정리",
        "Final Decision Entry Packet",
        "final decision entry packet은 activation approval, production readiness approval, stage/commit/push approval이 아니다",
        "final decision entry packet은 actual activation, production deployment, external provider expansion, stage/commit/push 승인으로 해석하지 않는다",
        "final decision entry packet은 141~150차 final decision 구간 진입 상태를 정리하는 review packet이며 execution packet이 아니다",
        "final decision entry packet keeps commit approval blocked and activation approval blocked",
        "final decision entry packet keeps evidence ready, disabled boundary ready, remaining Decision Required ready",
        "150차 Jarvis v2 완성권까지 9차 남음",
        "142차 Jarvis v2 Final Decision Approval Boundary Packet",
        "final decision approval boundary를 정리",
        "Final Decision Approval Boundary Packet",
        "final decision approval boundary는 user approval, Opus review, production readiness, stage/commit/push approval을 서로 분리",
        "approval boundary packet은 activation approval, production readiness approval, stage/commit/push approval이 아니다",
        "approval boundary packet은 user approval request를 execution approval로 승격하지 않는다",
        "approval boundary packet keeps git approval separate from activation approval",
        "approval boundary packet keeps Opus review gate separate from user final approval",
        "production readiness remains separate from public release evidence",
        "150차 Jarvis v2 완성권까지 8차 남음",
        "143차 Jarvis v2 Final Decision Evidence Packet",
        "final decision 구간 evidence packet을 정리",
        "Final Decision Evidence Packet",
        "evidence packet은 actual verification results, disabled boundary, remaining Decision Required, approval boundary를 함께 포함",
        "final decision evidence packet은 activation approval, production readiness approval, stage/commit/push approval이 아니다",
        "final decision evidence packet keeps approval boundary separate from verification evidence",
        "final decision evidence packet keeps commit approval blocked and activation approval blocked",
        "150차 Jarvis v2 완성권까지 7차 남음",
        "144차 Jarvis v2 Final Decision Release Lock Packet",
        "final decision release lock을 정리",
        "Final Decision Release Lock Packet",
        "release lock은 actual verification results, disabled boundary, remaining Decision Required, approval boundary, stage/commit/push 미수행을 함께 포함",
        "final decision release lock은 activation approval, production readiness approval, stage/commit/push approval이 아니다",
        "final decision release lock keeps verification evidence separate from activation approval",
        "final decision release lock keeps git approval blocked and activation approval blocked",
        "release lock은 user final approval, Opus review gate, production readiness, git approval을 서로 대체하지 않는다",
        "150차 Jarvis v2 완성권까지 6차 남음",
        "145차 Jarvis v2 Final Decision Commit Boundary Packet",
        "final decision commit boundary를 정리",
        "Final Decision Commit Boundary Packet",
        "commit boundary는 commit scope, commit message, push/PR 여부, staged diff 없음, stage/commit/push 미수행을 함께 포함",
        "commit boundary packet은 activation approval, production readiness approval, stage/commit/push approval이 아니다",
        "commit boundary packet keeps commit approval blocked until explicit user approval",
        "commit boundary packet keeps staged diff empty and stage/commit/push unperformed",
        "commit boundary packet keeps git approval separate from release readiness",
        "150차 Jarvis v2 완성권까지 5차 남음",
        "146차 Jarvis v2 Final Decision Verification Packet",
        "final decision verification 기준을 정리",
        "Final Decision Verification Packet",
        "verification packet은 full pytest, compileall, public release check, git diff --check, local CI, git status, staged diff 없음 guard를 함께 포함",
        "verification packet은 activation approval, production readiness approval, stage/commit/push approval이 아니다",
        "verification packet keeps test evidence separate from activation approval",
        "verification packet keeps public release evidence separate from production deployment approval",
        "verification packet keeps staged diff empty and stage/commit/push unperformed",
        "150차 Jarvis v2 완성권까지 4차 남음",
        "147차 Jarvis v2 Final Decision Status Freeze Packet",
        "final decision status를 동결",
        "Final Decision Status Freeze Packet",
        "status freeze는 completed stages, remaining stages, disabled boundary, remaining Decision Required, staged diff 없음, stage/commit/push 미수행을 함께 포함",
        "status freeze packet은 activation approval, production readiness approval, stage/commit/push approval이 아니다",
        "status freeze packet keeps completed stages separate from activation approval",
        "status freeze packet keeps remaining stages visible and not approved",
        "status freeze packet keeps staged diff empty and stage/commit/push unperformed",
        "completed stages는 1~147차 docs/test/review-required 중심 guard 완료 상태",
        "remaining stages는 148~150차 final decision closure prep, final packet, final handoff",
        "150차 Jarvis v2 완성권까지 3차 남음",
        "148차 권장 작업은 Jarvis v2 Final Decision Closure Prep Packet",
        "148차 Jarvis v2 Final Decision Closure Prep Packet",
        "final decision closure prep을 정리",
        "Final Decision Closure Prep Packet",
        "closure prep은 completed stages, remaining stages, final verification evidence, commit boundary, status freeze를 함께 포함",
        "closure prep packet은 activation approval, production readiness approval, stage/commit/push approval이 아니다",
        "closure prep packet keeps closure preparation separate from activation approval",
        "closure prep packet keeps final verification evidence separate from production deployment approval",
        "closure prep packet keeps commit boundary and status freeze visible",
        "completed stages는 1~148차 docs/test/review-required 중심 guard 완료 상태",
        "remaining stages는 149~150차 final packet, final handoff",
        "150차 Jarvis v2 완성권까지 2차 남음",
        "149차 권장 작업은 Jarvis v2 Final Decision Final Packet",
        "149차 Jarvis v2 Final Decision Final Packet",
        "final decision final packet을 정리",
        "Final Decision Final Packet",
        "final packet은 completed stages, final verification evidence, release lock, commit boundary, status freeze, remaining Decision Required를 함께 포함",
        "final packet은 activation approval, production readiness approval, stage/commit/push approval이 아니다",
        "final packet keeps final decision evidence separate from activation approval",
        "final packet keeps release lock separate from production deployment approval",
        "final packet keeps commit approval blocked and stage/commit/push unperformed",
        "completed stages는 1~149차 docs/test/review-required 중심 guard 완료 상태",
        "remaining stage는 150차 final handoff",
        "150차 Jarvis v2 완성권까지 1차 남음",
        "150차 권장 작업은 Jarvis v2 Final Handoff Packet",
        "150차 Jarvis v2 Final Handoff Packet",
        "Jarvis v2 완성권 final handoff를 정리",
        "Final Handoff Packet",
        "final handoff는 1~150차 completed stages, final verification evidence, disabled boundary, remaining Decision Required, commit/stage Decision Required, next human decision을 함께 포함",
        "final handoff packet은 activation approval, production readiness approval, stage/commit/push approval이 아니다",
        "final handoff keeps Jarvis v2 completion separate from activation approval",
        "final handoff keeps final verification evidence separate from production deployment approval",
        "final handoff keeps commit/stage Decision Required as the next human decision",
        "completed stages는 1~150차 docs/test/review-required 중심 guard 완료 상태",
        "150차 Jarvis v2 완성권 완료",
        "next human decision은 commit scope, commit message, push/PR 여부 승인",
        "stage/commit/push remains unperformed after Jarvis v2 final handoff",
        "151차 Commit / Stage Final Decision Required Packet",
        "Commit / Stage Final Decision Required Packet",
        "final handoff 이후 commit/stage/push 승인 경계를 최종 Decision Required로 재고정",
        "151차는 stage/commit/push 실행 단계가 아니다",
        "151차 packet은 activation approval, production readiness approval, stage/commit/push approval이 아니다",
        "commit scope는 사용자 최종 승인 필요",
        "commit message는 사용자 최종 승인 필요",
        "push/PR 여부는 사용자 최종 승인 필요",
        "staged diff 없음은 계속 유지",
        "stage/commit/push remains unperformed after stage151 decision packet",
        "멈추지 말고 해줘는 git stage/commit/push 명시 승인으로 해석하지 않는다",
        "next human decision remains commit scope, commit message, push/PR approval",
        "152차 Post-151 Commit Decision Hold Guard",
        "Post-151 Commit Decision Hold Guard",
        "151차 이후 사용자 승인 대기 상태를 유지",
        "152차는 commit hold guard이며 stage/commit/push 실행 단계가 아니다",
        "commit hold guard keeps staged diff empty",
        "commit hold guard keeps worktree unstaged until explicit approval",
        "commit hold guard keeps user approval separate from continue instruction",
        "commit hold guard keeps public release evidence separate from production deployment approval",
        "stage/commit/push remains unperformed after stage152 hold guard",
        "next human decision remains explicit commit scope, commit message, push/PR approval",
        "153차 Explicit Approval Awaiting Packet",
        "Explicit Approval Awaiting Packet",
        "사용자 최종 승인 대기 상태를 명시적으로 유지",
        "153차는 approval awaiting packet이며 stage/commit/push 실행 단계가 아니다",
        "explicit approval awaiting keeps continue wording separate from git approval",
        "explicit approval awaiting keeps commit scope unresolved",
        "explicit approval awaiting keeps commit message unresolved",
        "explicit approval awaiting keeps push/PR unresolved",
        "explicit approval awaiting keeps staged diff empty",
        "stage/commit/push remains unperformed after stage153 awaiting packet",
        "154차 Git Action Still Blocked Verification Packet",
        "Git Action Still Blocked Verification Packet",
        "git action still blocked 상태를 검증",
        "154차는 git action verification packet이며 stage/commit/push 실행 단계가 아니다",
        "git action still blocked keeps staged diff empty",
        "git action still blocked keeps commit scope unresolved",
        "git action still blocked keeps commit message unresolved",
        "git action still blocked keeps push/PR unresolved",
        "git action still blocked keeps worktree unstaged until explicit user approval",
        "stage/commit/push remains unperformed after stage154 verification packet",
        "155차 Commit Scope Still Unresolved Packet",
        "Commit Scope Still Unresolved Packet",
        "commit scope still unresolved 상태를 유지",
        "155차는 commit scope decision packet이며 stage/commit/push 실행 단계가 아니다",
        "commit scope still unresolved keeps staged diff empty",
        "commit scope still unresolved keeps commit message unresolved",
        "commit scope still unresolved keeps push/PR unresolved",
        "commit scope still unresolved keeps user approval required",
        "stage/commit/push remains unperformed after stage155 unresolved packet",
        "156차 Commit Message Still Unresolved Packet",
        "Commit Message Still Unresolved Packet",
        "commit message still unresolved 상태를 유지",
        "156차는 commit message decision packet이며 stage/commit/push 실행 단계가 아니다",
        "commit message still unresolved keeps staged diff empty",
        "commit message still unresolved keeps commit scope unresolved",
        "commit message still unresolved keeps push/PR unresolved",
        "commit message still unresolved keeps user approval required",
        "stage/commit/push remains unperformed after stage156 unresolved packet",
        "157차 Push PR Still Unresolved Packet",
        "Push PR Still Unresolved Packet",
        "push/PR still unresolved 상태를 유지",
        "157차는 push/PR decision packet이며 stage/commit/push 실행 단계가 아니다",
        "push/PR still unresolved keeps staged diff empty",
        "push/PR still unresolved keeps commit scope unresolved",
        "push/PR still unresolved keeps commit message unresolved",
        "push/PR still unresolved keeps user approval required",
        "stage/commit/push remains unperformed after stage157 unresolved packet",
        "158차 Final Approval Required Hold Packet",
        "Final Approval Required Hold Packet",
        "final approval required hold 상태를 유지",
        "158차는 final approval hold packet이며 stage/commit/push 실행 단계가 아니다",
        "final approval required keeps staged diff empty",
        "final approval required keeps commit scope unresolved",
        "final approval required keeps commit message unresolved",
        "final approval required keeps push/PR unresolved",
        "stage/commit/push remains unperformed after stage158 hold packet",
        "159차 Continue Instruction Is Not Git Approval Guard",
        "Continue Instruction Is Not Git Approval Guard",
        "continue instruction이 git stage/commit/push 승인으로 해석되지 않게",
        "159차는 continue-instruction guard이며 stage/commit/push 실행 단계가 아니다",
        "continue instruction keeps staged diff empty",
        "continue instruction keeps commit scope unresolved",
        "continue instruction keeps commit message unresolved",
        "continue instruction keeps push/PR unresolved",
        "continue instruction keeps user final approval required",
        "stage/commit/push remains unperformed after stage159 continue guard",
        "160차 Continue Still Not Git Approval Guard",
        "Continue Still Not Git Approval Guard",
        "반복된 \"멈추지 말고\" continue instruction도 git stage/commit/push 승인으로 해석되지 않게",
        "160차는 repeated-continue guard이며 stage/commit/push 실행 단계가 아니다",
        "repeated continue keeps staged diff empty",
        "repeated continue keeps commit scope unresolved",
        "repeated continue keeps commit message unresolved",
        "repeated continue keeps push/PR unresolved",
        "repeated continue keeps user final approval required",
        "stage/commit/push remains unperformed after stage160 repeated continue guard",
    ]:
        assert phrase in text


def test_public_release_summary_contract_snapshot_matches_runtime() -> None:
    text = SUMMARY.read_text(encoding="utf-8")
    runtime = build_api_inventory(app.routes)
    commands = get_command(cli_main.app).commands

    expected_rows = {
        "FastAPI endpoints": runtime["endpoints_count"],
        "Protected endpoints": runtime["protected_endpoints_count"],
        "Public endpoints": runtime["public_endpoints_count"],
        "Typer CLI commands": len(commands),
        "Document/RAG smoke steps": len(smoke.DOCUMENT_RAG_SMOKE_FLOW),
        "Assistant bridge smoke steps": len(smoke.ASSISTANT_BRIDGE_SMOKE_FLOW),
        "Assistant bridge preflight steps": len(smoke.ASSISTANT_BRIDGE_PREFLIGHT_FLOW),
    }

    assert "## Release Contract Snapshot" in text
    for label, value in expected_rows.items():
        assert f"| {label} | {value} |" in text


def test_release_checklist_requires_capability_boundary_self_check() -> None:
    text = Path("docs/RELEASE_CHECKLIST.md").read_text(encoding="utf-8")

    for phrase in [
        "Agent execution v1은 조건부 read-only 기능",
        "허용 root 폴더 목록 조회",
        "텍스트 파일 preview",
        "명시 URL 단건 read-only fetch",
        "폴더 UI 열기",
        "shell은 dry-run 정책 판단만",
    ]:
        assert phrase in text


def test_public_release_docs_share_next_improvement_boundaries() -> None:
    docs = {
        "docs/RELEASE_CHECKLIST.md": Path("docs/RELEASE_CHECKLIST.md").read_text(
            encoding="utf-8"
        ),
        "docs/PUBLIC_RELEASE_SUMMARY.md": SUMMARY.read_text(encoding="utf-8"),
    }

    required_phrases = [
        "Codex가 바로 이어서 할 수 있는 안전한 개선",
        "별도 승인 또는 보안 리뷰가 필요한 개선",
        "endpoint/response field 계약 테스트",
        "runtime endpoint count drift check",
        "README/Project Summary Runtime Contract Snapshot",
        "API/CLI/smoke flow inventory",
        "승인된 실제 사용자 `.md`, `.txt`, `.html`, `.htm`, `.pdf`, `.docx` 문서 E2E smoke summary",
        "민감 정보 없이 유지",
        "대용량 색인 job/status API",
        "progress response schema",
        "preview-only",
        "실제 queue 활성화 조건",
        "실제 rebuild 활성화 조건",
        "assistant bridge smoke expected output",
        "UI 수동 QA 체크리스트",
        "최신 preview endpoint 표시 기준",
        "실제 repair/delete/rebuild",
        "브라우저 click/fill/submit 자동화",
        "shell 실행",
        "파일 생성/수정/삭제 자동화",
        "PDF OCR fallback",
        "JavaScript 렌더링",
        "외부 URL 크롤링",
        "pdf2image/poppler",
        "운영 배포",
        "HTTPS termination",
        "다중 사용자 권한 관리",
        "분산 rate limit",
    ]

    for path, text in docs.items():
        for phrase in required_phrases:
            assert phrase in text, f"{path} missing next improvement boundary: {phrase}"
